In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/font_manager.py:229: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '


In [2]:
lowerlimit = 0      #set domain
upperlimit = 1.75
def cos(x):         #define function to integrate
    y = np.cos(x)
    return y

In [3]:
c = 0        #create variable to store our upper and lower range values
d = 0
def rangefinder():   #define function to find upper an lower range values
    xvals = np.linspace(lowerlimit, upperlimit, 10000)   #create x values
    yvals = []           #create an empty array to store y values
    for i in xvals:
        yvals.append(cos(i))    #add function values to empty y array
        
    ymin = min(yvals)       #find min of function values
    ymax = max(yvals)       #find max of function values
    
    global c        #pad values wih .5, store as global variables for later use
    c = ymin - .5    
    global d
    d = ymax + .5  
    
    return c, d      #return padded values
rangefinder()

(-0.678246055649492, 1.5)

In [5]:
n = 10000
x = np.random.uniform(lowerlimit,upperlimit,n)     #creates n random x values within domain
y = np.random.uniform(c,d,n)                    #creates n random y values within range

under = np.where(cos(x) > y)[0]
over = np.where(cos(x) <= y)[0]

print (x)
print (y)
print (under)
print (over)

[1.00320566 0.50817726 1.07337071 ... 0.68227475 1.08725442 0.23035573]
[ 1.03728025 -0.05788848 -0.17012663 ...  1.08143727  0.71568716
 -0.40831795]
[   1    2    5 ... 9994 9996 9999]
[   0    3    4 ... 9995 9997 9998]


In [6]:
frac = len(under)/(len(under)+len(over))    #defines ratio of integral values:non integral values
area = (d-c)*(upperlimit-lowerlimit)    #finds the area of the box (domain*range)
integral = area*frac                  #multiplies the area of the box*the integral ratio
print (frac)
print (c)
print(d)
print(area)
print (integral)

0.5639
-0.678246055649492
1.5
3.8119305973866107
2.1495476638663096
